(function(g){var window=this;var Npa=function(a,b){return g.Vb(a,b)},y5=function(){},Opa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Ppa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Fd&&"function"==typeof a.Fd)var c=a.Fd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Ma(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Opa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},z5=function(a){g.jn(a,"zx",g.dd());
return a},A5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.on(a.l,b,c)},B5=function(a){return(a=g.Ko(a))?new ActiveXObject(a):new XMLHttpRequest},C5=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},Qpa=function(a){return"content-type"==a.toLowerCase()},D5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Rpa=function(a){return g.Pd&&g.pd(9)&&g.Ga(a.timeout)&&g.Ea(a.ontimeout)},E5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},F5=function(a,b){if(a.g){D5(a);
var c=a.g,d=a.P[0]?g.Ia:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},G5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;E5(a);F5(a)},H5=function(a){return a.g?a.g.readyState:0},I5=function(a){if(a.i&&"undefined"!=typeof g.AY)if(a.P[1]&&4==H5(a)&&2==a.getStatus())C5(a,"Local request error detected and ignored");
else if(a.D&&4==H5(a))g.Kg(a.Zv,0,a);else if(a.dispatchEvent("readystatechange"),4==H5(a)){C5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ug(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Spa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<H5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";E5(a)}}finally{F5(a)}}},J5=function(a){g.Uf.call(this);
this.headers=new g.Ym;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Z="";this.I=this.R=!1},K5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Tpa=function(a,b){var c=[];
g.Wk(b,function(d){try{var e=g.Zo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Yo(e)&&c.push(d):c.push(d)},a);
return c},Upa=function(a,b){var c=Tpa(a,b);
(0,g.B)(c,function(d){g.Zo.prototype.remove.call(this,d)},a)},L5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},Vpa=function(a,b){g.$a(a,b)||a.push(b)},M5=function(a){var b=0,c;
for(c in a)b++;return b},N5=function(a,b){var c=b instanceof g.yc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},Wpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Xpa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Wpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Ypa=function(a,b,c,d){var e=new g.an(null,void 0);
a&&g.bn(e,a);b&&g.cn(e,b);c&&g.dn(e,c);d&&(e.i=d);return e},O5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Xpa(a)},P5=function(){this.g=[];
this.i=[]},Q5=function(a,b){g.dq[a]=!0;
var c=g.bq();c&&c.publish.apply(c,arguments);g.dq[a]=!1},R5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Ym;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Zpa(this,a.capabilities||""),$pa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Zpa=function(a,b){a.capabilities.clear();
(0,g.ae)(b.split(","),g.Ra(Npa,aqa)).forEach(function(c){a.capabilities.add(c)})},$pa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},S5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},T5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},U5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bqa=function(a){return new S5(a)},V5=function(a){return g.La(a)?(0,g.G)(a,bqa):[]},W5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},X5=function(a){return g.La(a)?"["+(0,g.G)(a,W5).join(",")+"]":"null"},Y5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},cqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},Z5=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$5=function(a,b){return g.Xa(a,function(c){return T5(c,b)})},dqa=function(){var a=(0,g.ut)();
a&&Upa(a,a.g.gf(!0))},a6=function(){var a=g.xt("yt-remote-connected-devices")||[];
g.qb(a);return a},eqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},b6=function(a){g.wt("yt-remote-connected-devices",a,86400)},d6=function(){if(c6)return c6;
var a=g.xt("yt-remote-device-id");a||(a=Y5(),g.wt("yt-remote-device-id",a,31536E3));for(var b=a6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return c6=d},e6=function(){var a=a6(),b=d6();
g.$a(a,b);g.At()&&g.sb(a,b);a=eqa(a);if(0==a.length)try{g.Bs("remote_sid")}catch(c){}else try{g.As("remote_sid",a.join(","),-1)}catch(c){}},f6=function(){return g.xt("yt-remote-session-browser-channel")},g6=function(){return g.xt("yt-remote-local-screens")||[]},h6=function(){g.wt("yt-remote-lounge-token-expiration",!0,86400)},fqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(g6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.kj)(c,function(d){return!g.$a(b,d)})&&h6();
g.wt("yt-remote-local-screens",a,31536E3)},gqa=function(a,b){g.wt("yt-remote-session-browser-channel",a);
g.wt("yt-remote-session-screen-id",b);var c=a6(),d=d6();g.$a(c,d)||c.push(d);b6(c);e6()},i6=function(a){a||(g.zt("yt-remote-session-screen-id"),g.zt("yt-remote-session-video-id"));
e6();a=a6();g.cb(a,d6());b6(a)},k6=function(){if(!j6){var a=g.ip();
a&&(j6=new g.To(a))}return j6?!!j6.get("yt-remote-use-staging-server"):!1},l6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},m6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},o6=function(a){a.length?n6(a.shift(),function(){o6(a)}):p6()},hqa=function(a){return"chrome-extension://"+a+q6},n6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},p6=function(){var a=m6();
a&&a(!1,"No cast extension found")},r6=function(){if(iqa){var a=2,b=m6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;n6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",p6,c)}},jqa=function(){r6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);o6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+q6,"//www.gstatic.com/eureka/clank"+q6])},s6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.WC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},t6=function(){},u6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.aa=new g.pn(this);this.i=new g.Jg;this.i.setInterval(250)},w6=function(a,b,c){a.Th=1;
a.fg=z5(b.clone());a.ph=c;a.u=!0;v6(a,null)},x6=function(a,b,c,d,e){a.Th=1;
a.fg=z5(b.clone());a.ph=null;a.u=c;e&&(a.Sz=!1);v6(a,d)},v6=function(a,b){a.yi=(0,g.D)();
y6(a);a.zg=a.fg.clone();A5(a.zg,"t",a.A);a.Uk=0;a.tc=a.g.qp(a.g.Kk()?b:null);0<a.Up&&(a.xn=new g.Jl((0,g.y)(a.aB,a,a.tc),a.Up));a.aa.da(a.tc,"readystatechange",a.CL);var c=a.Ug?g.cc(a.Ug):{};a.ph?(a.fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.zg,a.fo,a.ph,c)):(a.fo="GET",a.Sz&&!g.Rd&&(c.Connection="close"),a.tc.send(a.zg,a.fo,null,c));a.g.pe(1)},F6=function(a,b,c){for(var d=!0;!a.Kg&&a.Uk<c.length;){var e=kqa(a,c);
if(e==z6){4==b&&(a.gg=4,A6(15),d=!1);break}else if(e==B6){a.gg=4;A6(16);d=!1;break}else C6(a,e)}4==b&&0==c.length&&(a.gg=1,A6(17),d=!1);a.ue=a.ue&&d;d||(D6(a),E6(a))},kqa=function(a,b){var c=a.Uk,d=b.indexOf("\n",c);
if(-1==d)return z6;c=Number(b.substring(c,d));if(isNaN(c))return B6;d+=1;if(d+c>b.length)return z6;var e=b.substr(d,c);a.Uk=d+c;return e},I6=function(a,b){a.yi=(0,g.D)();
y6(a);var c=b?window.location.hostname:"";a.zg=a.fg.clone();g.jn(a.zg,"DOMAIN",c);g.jn(a.zg,"t",a.A);try{a.ye=new ActiveXObject("htmlfile")}catch(n){D6(a);a.gg=7;A6(22);E6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in G6)k=G6[l];else if(l in H6)k=G6[l]=H6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
G6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Tc(g.rc("b/12014412"),d+"</body></html>");a.ye.open();a.ye.write(g.Oc(c));a.ye.close();a.ye.parentWindow.m=(0,g.y)(a.XK,a);a.ye.parentWindow.d=(0,g.y)(a.Yy,a,!0);a.ye.parentWindow.rpcClose=(0,g.y)(a.Yy,a,!1);c=a.ye.createElement("DIV");a.ye.parentWindow.document.body.appendChild(c);d=g.Dc(a.zg.toString());d=g.$c(g.Ac(d));d=g.Tc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Uc(c,d);a.g.pe(1)},y6=function(a){a.gt=(0,g.D)()+a.o;
J6(a,a.o)},J6=function(a,b){if(null!=a.Pi)throw Error("WatchDog timer not null");
a.Pi=K6((0,g.y)(a.hL,a),b)},L6=function(a){a.Pi&&(g.w.clearTimeout(a.Pi),a.Pi=null)},E6=function(a){a.g.Xv()||a.Kg||a.g.gn(a)},D6=function(a){L6(a);
g.sf(a.xn);a.xn=null;a.i.stop();g.rn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.ye&&(a.ye=null)},C6=function(a,b){try{a.g.Sy(a,b),a.g.pe(4)}catch(c){}},N6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;M6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){N6(a,b,c,d,f)},f)})}},M6=function(a,b,c){var d=new Image;
d.onload=function(){try{O6(d),c(!0)}catch(e){}};
d.onerror=function(){try{O6(d),c(!1)}catch(e){}};
d.onabort=function(){try{O6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{O6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
N5(d,a)},O6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},P6=function(a){this.g=a;
this.i=new t6},R6=function(a){var b=Q6(a.g,a.aj,"/mail/images/cleardot.gif");
z5(b);N6(b.toString(),5E3,(0,g.y)(a.hC,a),3,2E3);a.pe(1)},T6=function(a){var b=a.g.F;
if(null!=b)A6(5),b?(A6(11),S6(a.g,a,!1)):(A6(12),S6(a.g,a,!0));else if(a.Bd=new u6(a,void 0,void 0,void 0),a.Bd.Ug=a.Sp,b=a.g,b=Q6(b,b.Kk()?a.Gj:null,a.Tp),A6(5),!g.Pd||g.qd(10))A5(b,"TYPE","xmlhttp"),x6(a.Bd,b,!1,a.Gj,!1);else{A5(b,"TYPE","html");var c=a.Bd;a=!!a.Gj;c.Th=3;c.fg=z5(b.clone());I6(c,a)}},U6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new t6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},lqa=function(a,b){this.g=a;
this.map=b;this.context=null},V6=function(a){g.uf.call(this,"statevent",a)},W6=function(a,b){g.uf.call(this,"timingevent",a);
this.size=b},X6=function(a){g.uf.call(this,"serverreachability",a)},a7=function(a){Y6(a);
if(3==a.g){var b=a.qk++,c=a.Ul.clone();g.jn(c,"SID",a.l);g.jn(c,"RID",b);g.jn(c,"TYPE","terminate");Z6(a,c);b=new u6(a,a.l,b,void 0);b.Th=2;b.fg=z5(c.clone());N5(new Image,b.fg.toString());b.yi=(0,g.D)();y6(b)}$6(a)},c7=function(a){a.zC(1,0);
a.Ul=Q6(a,null,a.Rp);b7(a)},Y6=function(a){a.Wf&&(a.Wf.abort(),a.Wf=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.jf&&(g.w.clearTimeout(a.jf),a.jf=null);d7(a);a.xd&&(a.xd.cancel(),a.xd=null);a.cg&&(g.w.clearTimeout(a.cg),a.cg=null)},e7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new lqa(a.iH++,b));2!=a.g&&3!=a.g||b7(a)},b7=function(a){a.xd||a.cg||(a.cg=K6((0,g.y)(a.Xy,a),0),a.Oh=0)},h7=function(a,b){if(1==a.g){if(!b){a.qk=Math.floor(1E5*Math.random());
var c=a.qk++,d=new u6(a,"",c,void 0);d.Ug=null;var e=f7(a),f=a.Ul.clone();g.jn(f,"RID",c);g.jn(f,"CVER","1");Z6(a,f);w6(d,f,e);a.xd=d;a.g=2}}else 3==a.g&&(b?g7(a,b):0==a.i.length||a.xd||g7(a))},g7=function(a,b){if(b)if(6<a.Lg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.qk-1;var d=f7(a)}else c=b.B,d=b.ph;else c=a.qk++,d=f7(a);var e=a.Ul.clone();g.jn(e,"SID",a.l);g.jn(e,"RID",c);g.jn(e,"AID",a.ci);Z6(a,e);c=new u6(a,a.l,c,a.Oh+1);c.Ug=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.xd=c;w6(c,e,d)},Z6=function(a,b){if(a.Tc){var c=a.Tc.Bv();
c&&g.Lb(c,function(d,e){g.jn(b,e,d)})}},f7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Lg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Lg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},i7=function(a){a.Rb||a.jf||(a.B=1,a.jf=K6((0,g.y)(a.Wy,a),0),a.Ih=0)},k7=function(a){if(a.Rb||a.jf||3<=a.Ih)return!1;
a.B++;a.jf=K6((0,g.y)(a.Wy,a),j7(a,a.Ih));a.Ih++;return!0},S6=function(a,b,c){a.co=c;
a.Ge=b.wf;a.A||c7(a)},d7=function(a){null!=a.Pg&&(g.w.clearTimeout(a.Pg),a.Pg=null)},j7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},m7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.gM,a);c||(c=new g.an("//www.google.com/images/cleardot.gif"),z5(c));M6(c.toString(),1E4,d)}else A6(2);l7(a,b)},l7=function(a,b){a.g=0;
a.Tc&&a.Tc.Bu(b);$6(a);Y6(a)},$6=function(a){a.g=0;
a.Ge=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.fp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.fp(b)}},Q6=function(a,b,c){var d=g.kn(c);
if(""!=d.g)b&&g.cn(d,b+"."+d.g),g.dn(d,d.u);else{var e=window.location;d=Ypa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.nj&&g.Lb(a.nj,function(f,k){g.jn(d,k,f)});
g.jn(d,"VER",a.Lg);Z6(a,d);return d},K6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},A6=function(a){n7.dispatchEvent(new V6(n7,a))},o7=function(){},mqa=function(a,b){this.action=a;
this.params=b||{}},p7=function(a,b){g.H.call(this);
this.g=new g.N(this.PK,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},q7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.So;this.i=new p7(this.LL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},nqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.co,sessionId:a.g.l,arrayId:a.g.ci}},r7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&h7(a.g),a7(a.g));a.D=0},s7=function(a){return!!a.g&&3==a.g.g},oqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},t7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},u7=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.fh(c+b,{})},v7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),pd:g.Ra(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wq(b,a)},pqa=function(){var a=w7;
x7();y7.push(a);z7(y7)},A7=function(a,b){x7();
var c=y7,d=qqa(a,String(b));0==c.length?rqa(d):(z7(c),(0,g.B)(c,function(e){e(d)}))},x7=function(){y7||(y7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",y7,void 0))},rqa=function(a){var b=(B7+1)%50;
B7=b;C7[b]=a;D7||(D7=49==b)},z7=function(a){var b=C7;
if(b[0]){var c=B7,d=D7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
C7=Array(50);B7=-1;D7=!1}},qqa=function(a,b){var c=((0,g.D)()-sqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},E7=function(a){g.Q.call(this);
this.B=a;this.g=[]},F7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},tqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ae)(a.g,function(f){return!!Z5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=F7(a,b[d])||c;return c},uqa=function(a,b){var c=a.g.length;
a.g=(0,g.ae)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},G7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},I7=function(a){E7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;H7(this);this.info("Initializing with "+X5(this.g))},J7=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=u7(a.l,"/pairing/get_lounge_token_batch");
v7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.gD,a),(0,g.y)(a.fD,a))}},H7=function(a){var b=V5(g6());
b=(0,g.ae)(b,function(c){return!c.uuid});
return tqa(a,b)},K7=function(a,b){fqa((0,g.G)(a.g,U5));
b&&h6()},M7=function(a,b){g.Q.call(this);
this.A=b;var c=g.xt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;L7("Initialized with "+g.Og(this.g))},N7=function(a,b,c){var d=u7(a.u,"/pairing/get_screen_availability");
v7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},O7=function(a,b){a:if(M5(b)!=M5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(L7("Updated online screens: "+g.Og(a.g)),a.g=b,a.N("screenChange"));vqa(a)},P7=function(a){isNaN(a.l)||g.aq(a.l);
a.l=g.Zp((0,g.y)(a.gs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},L7=function(a){A7("OnlineScreenService",a)},Q7=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},vqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.qb(a);a.length?g.wt("yt-remote-online-screen-ids",a.join(","),60):g.zt("yt-remote-online-screen-ids")},R7=function(a){E7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};wqa(this)},T7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Hd();if(k=(c?$5(k,c):null)||$5(k,b)){k.uuid=b;var l=S7(a,k);N7(a.i,l,function(m){e(m?l:null)})}else c?xqa(a,c,(0,g.y)(function(m){var n=S7(this,new S5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));N7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},yqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Wq(u7(a.A,"/pairing/get_lounge_token_batch"),e)},zqa=function(a){a.g=a.l.Hd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X5(a.g))},wqa=function(a){U7(a);
a.l=new I7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.pD,a));zqa(a);a.o=V5(g.xt("yt-remote-automatic-screen-cache")||[]);U7(a);a.info("Initializing automatic screens: "+X5(a.o));a.i=new M7(a.A,(0,g.y)(a.Hd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},S7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.wt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,U5)));U7(a);a.u[b.uuid]=b.id;g.wt("yt-remote-device-id-map",a.u,31536E3);return b},U7=function(a){a.u=g.xt("yt-remote-device-id-map")||{}},V7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},W7=function(a,b){A7(a.P,b)},X7=function(a,b){V7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.HM,this);this.u=(0,g.y)(this.sL,this);this.o=g.Zp((0,g.y)(function(){Aqa(this,null)},this),12E4)},Bqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.y)(function(){W7(this,"Failed to send message: getMdxSessionStatus.")},a)):W7(a,"Sending yt message without session: "+g.Og(b))},Aqa=function(a,b){g.aq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.hn,a),d=(0,g.y)(a.Kd,a);a.Qv(b,c,d,5)}}else a.Kd(Error("Waiting for session status timed out."))},Y7=function(a,b,c){V7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ia;this.A=NaN;this.I=(0,g.y)(this.KM,this);this.g=g.Ia},Cqa=function(a){a.g=a.F.fB(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ia;
this.hn(b)},a),(0,g.y)(function(b){this.g=g.Ia;
this.Kd(b)},a))},Dqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}k6()&&(b.env_useStageMdx=1);return g.dh(b)},Z7=function(a,b){V7.call(this,a,b,"ManualSession");
this.g=g.Zp((0,g.y)(this.fi,this,null),150)},$7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.YJ,this)},Eqa=function(a,b){return b?g.Xa(a.l,function(c){return T5(b,c.label)},a):null},a8=function(a){A7("Controller",a)},w7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},b8=function(a){return a.u||!!a.l.length||!!a.g},c8=function(a,b,c){b!=a.g&&(g.sf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Vy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.fi(null)):a.N("yt-remote-cast2-session-change",null))},Fqa=function(a){var b=a.i.eB(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&T5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Eqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lqa=function(a,b,c,d,e,f,k){Gqa()?Hqa(b,e,f,k)&&(e8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Iqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Iqa(a,c):(f8("Failed to load cast API: "+m),g8(!1),e8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Jqa(),c(!1))},d?g.lq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?jqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?p6():(r6(),o6(Kqa.map(hqa))))):d8("Cannot initialize because not running Chrome")},Jqa=function(){d8("dispose");
var a=h8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);Mqa(!1);g.gq(i8);i8.length=0},j8=function(){return!!g.xt("yt-remote-cast-installed")},Nqa=function(){var a=g.xt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Oqa=function(){d8("clearCurrentReceiver");
g.zt("yt-remote-cast-receiver")},Pqa=function(){return j8()?h8()?h8().getCastSession():(f8("getCastSelector: Cast is not initialized."),null):(f8("getCastSelector: Cast API is not installed!"),null)},l8=function(){j8()?h8()?k8()?(d8("Requesting cast selector."),h8().requestSession()):(d8("Wait for cast API to be ready to request the session."),i8.push(g.fq("yt-remote-cast2-api-ready",l8))):f8("requestCastSelector: Cast is not initialized."):f8("requestCastSelector: Cast API is not installed!")},m8=
function(a,b){k8()?h8().setConnectedScreenStatus(a,b):f8("setConnectedScreenStatus called before ready.")},Gqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.ex||a},Qqa=function(a,b){h8().init(a,b)},Hqa=function(a,b,c,d){var e=!1;
h8()||(a=new $7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.wt("yt-remote-cast-available",f);Q5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){d8("onReceiverSelected: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f);Q5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){d8("onReceiverResumed: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){d8("onSessionChange: "+W5(f));
f||g.zt("yt-remote-cast-receiver");Q5("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
d8("cloudview.createSingleton_: "+e);return e},h8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Iqa=function(a,b){g8(!0);
e8(!1);Qqa(a,function(c){c?(Mqa(!0),g.iq("yt-remote-cast2-api-ready")):(f8("Failed to initialize cast API."),g8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Jqa());b(c)})},d8=function(a){A7("cloudview",a)},f8=function(a){A7("cloudview",a)},g8=function(a){d8("setCastInstalled_ "+a);
g.wt("yt-remote-cast-installed",a)},k8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Mqa=function(a){d8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},e8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},n8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ie=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},o8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ie=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},p8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},q8=function(a,b){a.B=b;
a.A=(0,g.D)()},r8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},s8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o8(a)},t8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ie;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},v8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new P5;this.l=this.i=null;this.F=(0,g.y)(this.SH,this);this.B=(0,g.y)(this.tk,this);this.D=(0,g.y)(this.RH,this);this.H=(0,g.y)(this.eI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.jt,this),Rqa(this))):c=3;0!=c&&(b?this.jt(c):g.Zp((0,g.y)(function(){this.jt(c)},this),0));
var d=Pqa();d&&u8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},w8=function(a){return new n8(a.o.getPlayerContextData())},Rqa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.VJ,b),this))},a)},Sqa=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},x8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},z8=function(a,b,c){var d=w8(a);
q8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){Sqa(a);
a.o.setPlayerContextData(t8(b));Rqa(a)},u8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.tk(null));
a.l=b;a.l&&(A7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.tk(a.l.media[0]))},Tqa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=w8(a);b.contentId!=d.videoId&&A7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;q8(d,a.i.getEstimatedTime());y8(a,d)}else A7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},C8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.cs(window,"beforeunload",(0,g.y)(this.ZC,this)));this.i=[];this.Qa=new n8;this.V=b.id;this.g=Uqa(this,c);this.g.subscribe("handlerOpened",this.WH,this);this.g.subscribe("handlerClosed",this.TH,this);this.g.subscribe("handlerError",this.UH,this);this.g.subscribe("handlerMessage",this.VH,this);oqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.At()&&g.wt("yt-remote-session-video-id",d)},this)},D8=function(a){A7("conn",a)},Uqa=function(a,b){return new q7(u7(a.na,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},Vqa=function(a){a.u=g.Zp((0,g.y)(function(){D8("Connecting timeout");
this.A(1)},a),2E4)},F8=function(a){g.aq(a.u);
a.u=NaN},G8=function(a){g.aq(a.P);
a.P=NaN},Wqa=function(a){H8(a);
a.I=g.Zp((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.aq(a.I);
a.I=NaN},Yqa=function(a,b){b&&(F8(a),G8(a));
b==(s7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),E8(a,1),I8(a,"getNowPlaying"),Xqa(a)):a.A(1)},Zqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Yb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},$qa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;s8(a.Qa,c,d);a.N("remoteQueueChange")},bra=function(a,b){b.params=b.params||{};
$qa(a,b);ara(a,b);a.N("autoplayDismissed")},ara=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
q8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?Wqa(a):H8(a);a.N("remotePlayerChange")},cra=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);q8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},dra=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},era=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},fra=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ie="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},Xqa=function(a){g.aq(a.H);
a.H=g.Zp((0,g.y)(a.A,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.Og(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){E7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.FM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.zJ,this)))},kra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Rp("MDX_CONFIG")||b;dqa();e6();K8||(K8=new t7(b?b.loungeApiHost:void 0),k6()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",L8,void 0));gra();var c=M8();if(!c){var d=new R7(K8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lqa(a,d,function(m){m?N8()&&m8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){Q5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Og(b)),P8.push(g.fq("yt-remote-cast2-availability-change",function(){Q5("yt-remote-receiver-availability-change")})),P8.push(g.fq("yt-remote-cast2-receiver-selected",function(){Q8(null);
Q5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-receiver-resumed",function(){Q5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.fq("yt-remote-cast2-session-change",hra)),P8.push(g.fq("yt-remote-connection-change",function(m){m?m8(N8(),"YouTube TV"):R8()||(m8(null,null),Oqa())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Og(a)),ira(a),c.start(),N8()||jra())},mra=function(){var a=lra();
j8()&&g.xt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},lra=function(){var a=M8().Hc.$_gos();
var b=T8();b&&U8()&&(Z5(a,b)||a.push(b));return cqa(a)},V8=function(){var a=nra();
!a&&j8()&&Nqa()&&(a={key:"cast-selector-receiver",name:Nqa()});return a},nra=function(){var a=lra(),b=T8();
b||(b=R8());return g.Xa(a,function(c){return b&&T5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Hd();return $5(b,a)},hra=function(a){O8("remote.onCastSessionChange_: "+W5(a));
if(a){var b=T8();b&&b.id==a.id?m8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){k8()?h8().stopSession():f8("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){A7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},ora=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},pra=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||ora("");g.Ha("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?Q5("yt-remote-connection-change",!1):!b&&a&&Q5("yt-remote-connection-change",!0)},R8=function(){var a=g.At();
if(!a)return null;var b=M8().Hd();return $5(b,a)},X8=function(a,b){T8()&&T8();
ora(a.id);var c=new C8(K8,a,S8());c.connect(b,pra());c.subscribe("beforeDisconnect",function(d){Q5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},jra=function(){var a=R8();
a?(O8("Resume connection to: "+W5(a)),X8(a,0)):(i6(),Oqa(),O8("Skipping connecting because no session screen found."))},gra=function(){var a=S8();
if(g.Yb(a)){a=d6();var b=g.xt("yt-remote-session-name")||"",c=g.xt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},ira=function(a){a?(g.wt("yt-remote-session-app",a.app),g.wt("yt-remote-session-name",a.name)):(g.zt("yt-remote-session-app"),g.zt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ls(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.RI);this.l.K(b,"captionschanged",this.QH);this.l.K(b,"captionssettingschanged",this.sA);this.l.K(b,"videoplayerreset",this.jn);this.l.K(b,"mdxautoplaycancel",this.gC);this.O=this.l.K(b,"onVolumeChange",this.Gy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Ry,this);c.subscribe("remotePlayerChange",this.vk,this);c.subscribe("remoteQueueChange",this.jn,this);c.subscribe("autoplayUpNext",this.uy,
this);c.subscribe("previousNextChange",this.Oy,this);c.subscribe("nowAutoplaying",this.Ky,this);c.subscribe("autoplayDismissed",this.ty,this);this.suggestion=null;this.F=new g.yC(64);this.o=new g.N(this.qA,500,this);g.I(this,this.o);this.A=new g.N(this.rA,1E3,this);g.I(this,this.A);this.I=new s6(this.pM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.RA,1E3,this);g.I(this,this.P);this.H=new g.Jl(this.wF,1E3,this);g.I(this,this.H);this.M=g.Ia;this.sA();this.jn();this.vk()},b9=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},qra=function(a){b9(a,0);
a.o.stop();c9(a,new g.yC(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.gA(a.i.getVideoData(1).videoId,c);a.B=w8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.yf,L5(c));c9(a,new g.yC(1))},rra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{bQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return w8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.EC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.tK(a.i,d);a.F=b;sra(a.u,c,b)}},g9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.EP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.oQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);tra(this,g.pK(a))},tra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.DN('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.FC(b)||g.U(b,4)?g.DN('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.DN('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.WT.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.TK.call(this,a);
this.i={key:Y5(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.dk=new g.yC(64);this.D=0;this.zm=-1;if(!g.jz(g.Y(this.player))){a=this.player;var b=g.rD(a);b&&(b=b.Sm())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.FK(a,b.element,4)}},sra=function(a,b,c){a.dk=c;
a.player.N("presentingplayerstatechange",new g.FD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.yf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=L5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?
(Q8(d||null),k8()?h8().setLaunchParams(d||null):f8("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?Q5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Hd(),(d=$5(d,b.key))&&X8(d,1))}},Spa=/^https?$/i,ura=["POST",
"PUT"];g.A(J5,g.Uf);g.h=J5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?B5(this.M):B5(g.WY);this.P=this.M?this.M.getOptions():g.WY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Zv,this);try{y5(C5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){y5(C5(this,"Error opening Xhr: "+f.message));G5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Ppa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Fd(),Qpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(ura,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{D5(this),0<this.A&&(this.I=Rpa(this.g),y5(C5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.bw,this)):this.B=g.Kg(this.bw,this.A,this)),y5(C5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){y5(C5(this,"Send error: "+f.message)),G5(this,f)}};
g.h.bw=function(){"undefined"!=typeof g.AY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,C5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(C5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),F5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),F5(this,!0));J5.Ha.T.call(this)};
g.h.Zv=function(){this.ea()||(this.V||this.D||this.o?I5(this):this.XJ())};
g.h.XJ=function(){I5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<H5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var H6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},G6={"'":"\\'"},vra={};g.h=P5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Cma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var aqa={eN:"atp",oP:"ska",dP:"que",DO:"mus",nP:"sus",UN:"dsp",kP:"seq"};R5.prototype.Xf=function(){var a=new R5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var j6,c6="",q6=l6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",iqa=l6("loadCastFramework")||l6("loadCastApplicationFramework"),Kqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(s6,g.H);g.h=s6.prototype;g.h.VC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Vc:this.za=g.Kg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();s6.Ha.T.call(this)};
g.h.WC=function(){this.l?(this.za=g.Kg(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};t6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
t6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=u6.prototype;g.h.Ug=null;g.h.ue=!1;g.h.Pi=null;g.h.gt=null;g.h.yi=null;g.h.Th=null;g.h.fg=null;g.h.zg=null;g.h.ph=null;g.h.tc=null;g.h.Uk=0;g.h.ye=null;g.h.fo=null;g.h.gg=null;g.h.Hj=-1;g.h.Sz=!0;g.h.Kg=!1;g.h.Up=0;g.h.xn=null;var B6={},z6={};g.h=u6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.CL=function(a){a=a.target;var b=this.xn;b&&3==H5(a)?b.Dj():this.aB(a)};
g.h.aB=function(a){try{if(a==this.tc)a:{var b=H5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Pd&&!g.qd(10)||g.Rd&&!g.pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!K5(this.tc))break a;this.Kg||4!=b||7==c||(8==c||0>=d?this.g.pe(3):this.g.pe(2));L6(this);var e=this.tc.getStatus();this.Hj=e;var f=K5(this.tc);(this.ue=200==e)?(4==b&&D6(this),this.u?(F6(this,b,f),g.Fh&&this.ue&&3==b&&(this.aa.da(this.i,"tick",this.yL),this.i.start())):C6(this,f),this.ue&&!this.Kg&&(4==b?this.g.gn(this):(this.ue=
!1,y6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.gg=3,A6(13)):(this.gg=0,A6(14)),D6(this),E6(this))}}catch(k){this.tc&&K5(this.tc)}finally{}};
g.h.yL=function(){var a=H5(this.tc),b=K5(this.tc);this.Uk<b.length&&(L6(this),F6(this,a,b),this.ue&&4!=a&&y6(this))};
g.h.XK=function(a){K6((0,g.y)(this.WK,this,a),0)};
g.h.WK=function(a){this.Kg||(L6(this),C6(this,a),y6(this))};
g.h.Yy=function(a){K6((0,g.y)(this.VK,this,a),0)};
g.h.VK=function(a){this.Kg||(D6(this),this.ue=a,this.g.gn(this),this.g.pe(4))};
g.h.cancel=function(){this.Kg=!0;D6(this)};
g.h.hL=function(){this.Pi=null;var a=(0,g.D)();0<=a-this.gt?(2!=this.Th&&this.g.pe(3),D6(this),this.gg=2,A6(18),E6(this)):J6(this,this.gt-a)};
g.h.getLastError=function(){return this.gg};g.h=P6.prototype;g.h.Sp=null;g.h.Bd=null;g.h.yn=!1;g.h.Yv=null;g.h.Sl=null;g.h.Jq=null;g.h.Tp=null;g.h.Yd=null;g.h.wf=-1;g.h.Gj=null;g.h.aj=null;g.h.connect=function(a){this.Tp=a;a=Q6(this.g,null,this.Tp);A6(3);this.Yv=(0,g.D)();var b=this.g.D;null!=b?(this.Gj=b[0],(this.aj=b[1])?(this.Yd=1,R6(this)):(this.Yd=2,T6(this))):(A5(a,"MODE","init"),this.Bd=new u6(this,void 0,void 0,void 0),this.Bd.Ug=this.Sp,x6(this.Bd,a,!1,null,!0),this.Yd=0)};
g.h.hC=function(a){if(a)this.Yd=2,T6(this);else{A6(4);var b=this.g;b.Ge=b.Wf.wf;m7(b,9)}a&&this.pe(2)};
g.h.qp=function(a){return this.g.qp(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.wf=-1};
g.h.Xv=function(){return!1};
g.h.Sy=function(a,b){this.wf=a.Hj;if(0==this.Yd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ge=this.wf;m7(c,2);return}this.Gj=c[0];this.aj=c[1]}else c=this.g,c.Ge=this.wf,m7(c,2);else if(2==this.Yd)if(this.yn)A6(7),this.Jq=(0,g.D)();else if("11111"==b){if(A6(6),this.yn=!0,this.Sl=(0,g.D)(),c=this.Sl-this.Yv,!g.Pd||g.qd(10)||500>c)this.wf=200,this.Bd.cancel(),A6(12),S6(this.g,this,!0)}else A6(8),this.Sl=this.Jq=(0,g.D)(),this.yn=!1};
g.h.gn=function(){this.wf=this.Bd.Hj;if(this.Bd.ue)0==this.Yd?this.aj?(this.Yd=1,R6(this)):(this.Yd=2,T6(this)):2==this.Yd&&((!g.Pd||g.qd(10)?!this.yn:200>this.Jq-this.Sl)?(A6(11),S6(this.g,this,!1)):(A6(12),S6(this.g,this,!0)));else{0==this.Yd?A6(9):2==this.Yd&&A6(10);var a=this.g;this.Bd.getLastError();a.Ge=this.wf;m7(a,2)}};
g.h.Kk=function(){return this.g.Kk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.pe=function(a){this.g.pe(a)};g.h=U6.prototype;g.h.nj=null;g.h.xd=null;g.h.Rb=null;g.h.Rp=null;g.h.Ul=null;g.h.tu=null;g.h.hm=null;g.h.qk=0;g.h.iH=0;g.h.Tc=null;g.h.cg=null;g.h.jf=null;g.h.Pg=null;g.h.Wf=null;g.h.co=null;g.h.ci=-1;g.h.Fw=-1;g.h.Ge=-1;g.h.Oh=0;g.h.Ih=0;g.h.Lg=8;var n7=new g.Uf;g.A(V6,g.uf);g.A(W6,g.uf);g.A(X6,g.uf);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){A6(0);this.Rp=b;this.nj=c||{};d&&g.Ea(e)&&(this.nj.OSID=d,this.nj.OAID=e);this.A?(K6((0,g.y)(this.Ju,this,a),100),c7(this)):this.Ju(a)};
g.h.Ju=function(a){this.Wf=new P6(this);this.Wf.Sp=null;this.Wf.i=this.u;this.Wf.connect(a)};
g.h.Xv=function(){return 0==this.g};
g.h.Xy=function(a){this.cg=null;h7(this,a)};
g.h.Wy=function(){this.jf=null;this.Rb=new u6(this,this.l,"rpc",this.B);this.Rb.Ug=null;this.Rb.Up=0;var a=this.tu.clone();g.jn(a,"RID","rpc");g.jn(a,"SID",this.l);g.jn(a,"CI",this.co?"0":"1");g.jn(a,"AID",this.ci);Z6(this,a);if(!g.Pd||g.qd(10))g.jn(a,"TYPE","xmlhttp"),x6(this.Rb,a,!0,this.hm,!1);else{g.jn(a,"TYPE","html");var b=this.Rb,c=!!this.hm;b.Th=3;b.fg=z5(a.clone());I6(b,c)}};
g.h.Sy=function(a,b){if(0!=this.g&&(this.Rb==a||this.xd==a))if(this.Ge=a.Hj,this.xd==a&&3==this.g)if(7<this.Lg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.jf){if(this.Rb)if(this.Rb.yi+3E3<this.xd.yi)d7(this),this.Rb.cancel(),this.Rb=null;else break a;k7(this);A6(19)}}else this.Fw=c[1],0<this.Fw-this.ci&&37500>c[2]&&this.co&&0==this.Ih&&!this.Pg&&(this.Pg=K6((0,g.y)(this.MH,this),6E3));else m7(this,11)}else b!=vra.zN.g&&m7(this,11);else if(this.Rb==a&&
d7(this),!g.wb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.ci=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.hm=e[2],e=e[3],null!=e?this.Lg=e:this.Lg=6,this.g=3,this.Tc&&this.Tc.Du(),this.tu=Q6(this,this.Kk()?this.hm:null,this.Rp),i7(this)):"stop"==e[0]&&m7(this,7):3==this.g&&("stop"==e[0]?m7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Cu(e),this.Ih=0)}}};
g.h.MH=function(){null!=this.Pg&&(this.Pg=null,this.Rb.cancel(),this.Rb=null,k7(this),A6(20))};
g.h.gn=function(a){if(this.Rb==a){d7(this);this.Rb=null;var b=2}else if(this.xd==a)this.xd=null,b=1;else return;this.Ge=a.Hj;if(0!=this.g)if(a.ue)1==b?(b=(0,g.D)()-a.yi,n7.dispatchEvent(new W6(n7,a.ph?a.ph.length:0,b,this.Oh)),b7(this),this.o.length=0):i7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ge)){if(d=1==b)this.xd||this.cg||1==this.g||2<=this.Oh?d=!1:(this.cg=K6((0,g.y)(this.Xy,this,a),j7(this,this.Oh)),this.Oh++,d=!0);d=!(d||2==b&&k7(this))}if(d)switch(c){case 1:m7(this,
5);break;case 4:m7(this,10);break;case 3:m7(this,6);break;case 7:m7(this,12);break;default:m7(this,2)}}};
g.h.zC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.gM=function(a){a?A6(2):(A6(1),l7(this,8))};
g.h.qp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new J5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.pe=function(a){n7.dispatchEvent(new X6(n7,a))};
g.h.Kk=function(){return!(!g.Pd||g.qd(10))};
g.h=o7.prototype;g.h.Du=function(){};
g.h.Cu=function(){};
g.h.Bu=function(){};
g.h.fp=function(){};
g.h.Bv=function(){return{}};
g.h.isActive=function(){return!0};g.A(p7,g.H);g.h=p7.prototype;g.h.PK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.xo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(q7,o7);g.h=q7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Ef=function(a){return this.l.Vg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.sf(this.l),r7(this),g.sf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ci):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):s7(this)&&e7(this.g,c)};
g.h.Du=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)e7(this.g,a[b])}this.N("handlerOpened")};
g.h.Bu=function(a){var b=2==a&&401==this.g.Ge;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.fp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Bv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Cu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),a7(this.g)):this.N("handlerMessage",new mqa(a[0],a[1]))};
g.h.LL=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.xd&&b++;0==b&&this.connect(this.u,this.o)};t7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
t7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
t7.prototype.u=function(a){a(Error("request timed out"))};var sqa=(0,g.D)(),y7=null,C7=Array(50),B7=-1,D7=!1;g.A(E7,g.Q);E7.prototype.Hd=function(){return this.g};
E7.prototype.contains=function(a){return!!Z5(this.g,a)};
E7.prototype.get=function(a){return a?$5(this.g,a):null};
E7.prototype.info=function(a){A7(this.B,a)};g.A(G7,g.Q);var wra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=G7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.dB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.aq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();G7.Ha.T.call(this)};
g.h.dB=function(){this.za=NaN;this.g=g.Wq(u7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.DM,this),onError:(0,g.y)(this.CM,this),pd:(0,g.y)(this.EM,this)})};
g.h.DM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new S5(c))};
g.h.CM=function(a){this.g=null;a.status&&404==a.status?this.i>=wra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=wra[this.i],this.za=g.Zp((0,g.y)(this.dB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.EM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(I7,E7);g.h=I7.prototype;g.h.start=function(){H7(this)&&this.N("screenChange");!g.xt("yt-remote-lounge-token-expiration")&&J7(this);g.aq(this.i);this.i=g.Zp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){H7(this);F7(this,a);K7(this,!1);this.N("screenChange");b(a);a.token||J7(this)};
g.h.remove=function(a,b){var c=H7(this);uqa(this,a)&&(K7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Yn=function(a,b,c,d){var e=H7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,K7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.aq(this.i);I7.Ha.T.call(this)};
g.h.gD=function(a){H7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}K7(this,!b);b&&A7(this.B,"Missed "+b+" lounge tokens.")};
g.h.fD=function(a){A7(this.B,"Requesting lounge tokens failed: "+a)};g.A(M7,g.Q);g.h=M7.prototype;g.h.start=function(){var a=parseInt(g.xt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?P7(this):(this.o=(0,g.D)()+3E5,g.wt("yt-remote-fast-check-period",this.o),this.gs())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){L7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!$5(a,d)},this);
O7(this,b)};
g.h.T=function(){g.aq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);M7.Ha.T.call(this)};
g.h.gs=function(){g.aq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Q7(this);if(M5(a)){var b=u7(this.u,"/pairing/get_screen_availability");this.i=v7(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.y)(this.tK,this,a),(0,g.y)(this.sK,this))}else O7(this,{}),P7(this)};
g.h.tK=function(a,b){this.i=null;var c=g.Sb(Q7(this));if(g.rb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;O7(this,d);P7(this)}else this.Jb("Changing Screen set during request."),this.gs()};
g.h.sK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;P7(this)};
g.h.Jb=function(a){A7("OnlineScreenService",a)};g.A(R7,E7);g.h=R7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Yn=function(a,b,c,d){this.l.contains(a)?this.l.Yn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,A7(this.B,a),d(Error(a)))};
g.h.Hd=function(a){return a?this.g:g.fb(this.g,(0,g.ae)(this.o,function(b){return!this.contains(b)},this))};
g.h.eB=function(){return(0,g.ae)(this.Hd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.fB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new G7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.sf(f);d(S7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.sf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.GM=function(a,b,c,d){g.Wq(u7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new S5(f.screen||{});if(!k.name||yqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);yqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(S7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
pd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.sf(this.l);g.sf(this.i);R7.Ha.T.call(this)};
g.h.pD=function(){zqa(this);this.N("screenChange");this.i.update()};
R7.prototype.dispose=R7.prototype.dispose;g.A(V7,g.Q);g.h=V7.prototype;g.h.hn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Kd=function(a){this.ea()||(a&&W7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){A7(this.P,a)};
g.h.hB=function(){return null};
g.h.xs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){W7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.xs("");V7.Ha.T.call(this)};g.A(X7,V7);g.h=X7.prototype;g.h.ws=function(a){if(this.g){if(this.g==a)return;W7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Bqa(this)};
g.h.fi=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Kd()},this),(0,g.y)(function(){this.Kd(Error("Failed to stop receiver app."))},this)):this.Kd(Error("Stopping cast device witout session."))};
g.h.xs=g.Ia;g.h.T=function(){this.info("disposeInternal");g.aq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;X7.Ha.T.call(this)};
g.h.sL=function(a,b){if(!this.ea())if(b){var c=O5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":Aqa(this,c.screenId);break;default:W7(this,"Unknown youtube message: "+d)}}else W7(this,"Unable to parse message.")}else W7(this,"No data in message.")};
g.h.Qv=function(a,b,c,d){T7(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(W7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zp((0,g.y)(this.Qv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.hB=function(){return this.g};
g.h.HM=function(a){this.ea()||a||(W7(this,"Cast session died."),this.Kd())};g.A(Y7,V7);g.h=Y7.prototype;g.h.ws=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.fi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.aq(this.A);this.o?this.o.stop((0,g.y)(this.Kd,this,null),(0,g.y)(this.Kd,this,"Failed to stop DIAL device.")):this.Kd()};
g.h.T=function(){this.g();this.g=g.Ia;g.aq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;Y7.Ha.T.call(this)};
g.h.KM=function(a){this.ea()||a||(W7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Kd())};
g.h.jq=function(a){this.H=Y5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Dqa(this));a(b);Cqa(this)}else this.B=(0,g.y)(function(){g.aq(this.A);this.B=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Dqa(this));a(c);Cqa(this)},this),this.A=g.Zp((0,g.y)(function(){this.B()},this),100)};
g.h.MD=function(a,b,c){T7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.hn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.jq(b,c)},this),(0,g.y)(function(d){W7(this,"Failed to get DIAL screen: "+d);
this.jq(b,c)},this))};g.A(Z7,V7);Z7.prototype.stop=function(){this.Kd()};
Z7.prototype.ws=g.Ia;Z7.prototype.fi=function(){g.aq(this.g);this.g=NaN;var a=$5(this.F.Hd(),this.i.label);a?this.hn(a):this.Kd(Error("No such screen"))};
Z7.prototype.T=function(){g.aq(this.g);this.g=NaN;Z7.Ha.T.call(this)};g.A($7,g.Q);g.h=$7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Uy,this),(0,g.y)(this.cK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.mI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),pqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.gB,this)),this.l=Fqa(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Og(f))},this)),this.N("yt-remote-cast2-availability-change",b8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Og(f));
b(!1)},this))};
g.h.UL=function(a,b){a8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)a8("Unsetting old screen status: "+this.g.i.friendlyName),c8(this,null)}if(a&&b){if(!this.g){c=$5(this.i.Hd(),a);if(!c){a8("setConnectedScreenStatus: Unknown screen.");return}var d=Eqa(this,c);d||(a8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Og(e))},this)));
a8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);c8(this,new Z7(this.i,d),!0)}this.g.xs(b)}else a8("setConnectedScreenStatus: no screen.")};
g.h.VL=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.fi(a):this.Jb("Setting connection data without a session")};
g.h.JM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),c8(this,null)):a8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Uy,this),(0,g.y)(this.yK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.gB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],w7);g.sf(this.g);$7.Ha.T.call(this)};
g.h.Jb=function(a){A7("Controller",a)};
g.h.Vy=function(a,b){this.g==a&&(b||c8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.YJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),a8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)a8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{a8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:c8(this,
new Z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:c8(this,new Y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:c8(this,new X7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.mI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return a8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);c8(this,new Y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.MD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.jq,b))};
g.h.Uy=function(a){if(!this.ea()){a8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)a8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),c8(this,new X7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=$5(this.i.Hd(),c.label);d&&T5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(a8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.sf(this.g),this.g=new X7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Vy,this,this.g)),this.g.fi(null));this.g.ws(a)}}};
g.h.IM=function(){return this.g?this.g.hB():null};
g.h.yK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Og(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&c8(this,null))};
g.h.cK=function(a){a8("Receiver availability updated: "+a);if(!this.ea()){var b=b8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;b8(this)!=b&&this.N("yt-remote-cast2-availability-change",b8(this))}};
g.h.gB=function(){this.ea()||(this.l=Fqa(this),a8("Updating custom receivers: "+g.Og(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",b8(this)))};
$7.prototype.setLaunchParams=$7.prototype.VL;$7.prototype.setConnectedScreenStatus=$7.prototype.UL;$7.prototype.stopSession=$7.prototype.JM;$7.prototype.getCastSession=$7.prototype.IM;$7.prototype.requestSession=$7.prototype.requestSession;$7.prototype.init=$7.prototype.init;$7.prototype.dispose=$7.prototype.dispose;var i8=[];n8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ie=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
n8.prototype.isAdPlaying=function(){return 1081==this.playerState};
n8.prototype.getDuration=function(){return this.u?this.D+p8(this):this.D};
n8.prototype.clone=function(){return new n8(t8(this))};g.A(v8,g.Q);g.h=v8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,B8(this,"play")):A8(this,"play"),z8(this,1,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,B8(this,"pause")):A8(this,"pause"),z8(this,2,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=w8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,B8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.N("remotePlayerChange")}else x8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,B8(this,"stopVideo")):A8(this,"stopVideo");var a=w8(this);a.index=-1;a.videoId="";o8(a);y8(this,a);this.N("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=w8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){A7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){A7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Ra(this.setVolume,a,b))};
g.h.gA=function(a,b){if(1==this.g){var c=w8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Og(b.style),g.fc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Ra(this.gA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=w8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=w8(this);c=c||0;var m={videoId:a,currentIndex:c};s8(l,a,c);g.Ea(b)&&(q8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Og(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.tn=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Ra(this.tn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Ra(this.nextVideo,a,b))};
g.h.bv=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.bv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}v8.Ha.dispose.call(this)};
g.h.T=function(){Sqa(this);this.o=null;this.u.clear();u8(this,null);v8.Ha.T.call(this)};
g.h.jt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.VJ=function(a,b){this.N(a,b)};
g.h.SH=function(a){if(!a)this.tk(null),u8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=w8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)A7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.tk=function(a){A7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Tqa(this),this.N("remotePlayerChange")};
g.h.RH=function(a){a?(Tqa(this),this.N("remotePlayerChange")):this.tk(null)};
g.h.Os=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.eI=function(){var a=Pqa();a&&u8(this,a)};
g.h.Jb=function(a){A7("CP",a)};g.A(C8,g.Q);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;q8(this.Qa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.Og(l));this.g.connect({method:"setPlaylist",
params:g.Og(l)},a,f6())}else D8("Connecting without params"),this.g.connect({},a,f6());Vqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),E8(this,3));C8.Ha.dispose.call(this)};
g.h.T=function(){F8(this);H8(this);G8(this);g.aq(this.F);this.F=NaN;g.aq(this.H);this.H=NaN;this.l=null;g.ds(this.O);this.O.length=0;this.g.dispose();C8.Ha.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.ZC=function(){this.A(2)};
g.h.WH=function(){D8("Channel opened");this.M&&(this.M=!1,G8(this),this.P=g.Zp((0,g.y)(function(){D8("Timing out waiting for a screen.");this.A(1)},this),15E3));
gqa(nqa(this.g),this.V)};
g.h.TH=function(){D8("Channel closed");isNaN(this.u)?i6(!0):i6();this.dispose()};
g.h.UH=function(a){i6();isNaN(this.D())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,D8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),E8(this,2))};
g.h.VH=function(a){a.params?D8("Received: action="+a.action+", params="+g.Og(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=O5(a.params.devices);this.i=(0,g.G)(a,function(c){return new R5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Yqa(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Yqa(this,!1);break;case "remoteConnected":var b=new R5(O5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Vpa(this.i,b);
break;case "remoteDisconnected":b=new R5(O5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":$qa(this,a);break;case "nowPlaying":bra(this,a);break;case "onStateChange":ara(this,a);break;case "onAdStateChange":cra(this,a);break;case "onVolumeChanged":dra(this,a);break;case "onSubtitlesTrackChanged":Zqa(this,a);break;case "nowAutoplaying":era(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":fra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.IL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&I8(this,"getNowPlaying")}};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Ef;C8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?s7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
C8.prototype.getProxyState=C8.prototype.ca;C8.prototype.A=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&i6();r7(this.g,a);this.dispose()};
C8.prototype.disconnect=C8.prototype.A;C8.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),s8(a,this.l,a.index));return t8(a)};
C8.prototype.getPlayerContextData=C8.prototype.X;
C8.prototype.ka=function(a){var b=new n8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.aq(this.F),this.F=g.Zp((0,g.y)(this.IL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&r8(this.Qa)==r8(b)&&g.Og(this.Qa.g)==g.Og(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
C8.prototype.setPlayerContextData=C8.prototype.ka;C8.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
C8.prototype.getOtherConnectedRemoteId=C8.prototype.R;C8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
C8.prototype.getReconnectTimeout=C8.prototype.D;C8.prototype.ba=function(){return this.o||"UNSUPPORTED"};
C8.prototype.getAutoplayMode=C8.prototype.ba;C8.prototype.Z=function(){return this.B||""};
C8.prototype.getAutoplayVideoId=C8.prototype.Z;C8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.yo(a.g);a.start()}};
C8.prototype.reconnect=C8.prototype.va;C8.prototype.ia=function(a,b){I8(this,a,b);Xqa(this)};
C8.prototype.sendMessage=C8.prototype.ia;g.A(J8,E7);g.h=J8.prototype;g.h.Hd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;J8.Ha.T.call(this)};
g.h.FM=function(){this.N("screenChange")};
g.h.zJ=function(){this.N("onlineScreenChange")};
R7.prototype.$_st=R7.prototype.start;R7.prototype.$_gspc=R7.prototype.GM;R7.prototype.$_gsppc=R7.prototype.fB;R7.prototype.$_c=R7.prototype.contains;R7.prototype.$_g=R7.prototype.get;R7.prototype.$_a=R7.prototype.add;R7.prototype.$_un=R7.prototype.Yn;R7.prototype.$_r=R7.prototype.remove;R7.prototype.$_gs=R7.prototype.Hd;R7.prototype.$_gos=R7.prototype.eB;R7.prototype.$_s=R7.prototype.subscribe;R7.prototype.$_ubk=R7.prototype.Ef;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Ry,this);this.g.unsubscribe("remotePlayerChange",this.vk,this);this.g.unsubscribe("remoteQueueChange",this.jn,this);this.g.unsubscribe("autoplayUpNext",this.uy,this);this.g.unsubscribe("previousNextChange",this.Oy,this);this.g.unsubscribe("nowAutoplaying",this.Ky,this);this.g.unsubscribe("autoplayDismissed",this.ty,this);this.g=this.u=null};
g.h.tx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!w8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==w8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Dj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.QH=function(a){this.I.VC(a)};
g.h.pM=function(a){this.tx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.sA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||e9(this,a)};
g.h.Gy=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.vk,this);var b=Math.round(a.volume);a=!!a.muted;var c=w8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.vk,this)}};
g.h.RI=function(){g.Yb(this.B)||rra(this,this.B);this.D=!1};
g.h.Ry=function(a,b){this.A.stop();2==b&&this.rA()};
g.h.vk=function(){if(d9(this)){this.o.stop();var a=w8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.zm=1;break;case 1082:case 1083:this.u.zm=0;break;default:this.u.zm=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.yC(8));this.qA();break;case 1085:case 3:c9(this,new g.yC(9));break;case 1083:case 0:c9(this,new g.yC(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.yC(4));break;case 2:c9(this,new g.yC(4));b9(this,r8(a));
break;case -1:c9(this,new g.yC(64));break;case -1E3:c9(this,new g.yC(128,{errorCode:"mdx.remoteerror",message:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=w8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.B=a,rra(this,a));a=w8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.RA()}else qra(this)};
g.h.Oy=function(){this.i.N("mdxpreviousnextchange")};
g.h.jn=function(){d9(this)||qra(this)};
g.h.gC=function(){this.g.bv()};
g.h.uy=function(a){a&&(a=g.Wq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.aL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.aL=function(a,b){var c=new g.jB(g.Y(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Ky=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.ty=function(){this.i.N("mdxautoplaycanceled")};
g.h.wF=function(a,b){-1==w8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.RA=function(){if(d9(this)){var a=w8(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Gy)}};
g.h.qA=function(){this.o.stop();if(!this.g.ea()){var a=w8(this.g);1==a.playerState&&c9(this,new g.yC(8));b9(this,r8(a));this.o.start()}};
g.h.rA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.W);g9.prototype.u=function(a){tra(this,a.state)};g.t(h9,g.WT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.XT(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.oe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.ne=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.F[a].name};
h9.prototype.Jc=function(a){g.WT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.TK);g.h=i9.prototype;g.h.create=function(){kra(g.bz(g.Y(this.player)));this.u.push(g.fq("yt-remote-before-disconnect",this.NH,this));this.u.push(g.fq("yt-remote-connection-change",this.dK,this));this.u.push(g.fq("yt-remote-receiver-availability-change",this.Py,this));this.u.push(g.fq("yt-remote-auto-connect",this.bK,this));this.u.push(g.fq("yt-remote-receiver-resumed",this.aK,this));this.Py()};
g.h.load=function(){this.player.cancelPlayback();g.TK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=pra())?a.currentTime:0;var b=Z8()?new v8(U8(),void 0):null;0==a&&b&&(a=r8(w8(b)));0!=a&&this.qd(a);sra(this,this.dk,this.dk);g.WX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.tf(this.o,this.g);this.g=this.o=null;g.TK.prototype.unload.call(this);g.WX(this.player.app,5)};
g.h.T=function(){g.gq(this.u);g.TK.prototype.T.call(this)};
g.h.Te=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.tx.apply(this.o,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.zm};
g.h.RC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ie=function(){return this.g?w8(this.g).Ie:!1};
g.h.hasNext=function(){return this.g?w8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=w8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.Y(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+p8(a):a.l,isAtLiveHead:1>=(a.u?a.i+p8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+p8(a):a.i,seekableStart:0<a.o?a.o+
p8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.tn=function(){this.g&&this.g.tn()};
g.h.NH=function(a){1==a&&(this.B=this.g?w8(this.g):null)};
g.h.dK=function(){var a=Z8()?new v8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.sf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,r8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Py=function(){this.A=[this.i].concat(mra());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.bK=function(){var a=V8();j9(this,a)};
g.h.aK=function(){this.l=V8()};
g.h.ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&l8(),!0):!1}};
g.h.Os=function(){this.g.Os()};
g.h.Mb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.mV.remote=i9;})(_yt_player);
